from math import pi


SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800-60

TILE_SIZE = 60
NROWS = SCREEN_HEIGHT // TILE_SIZE
NCOLS = SCREEN_WIDTH // TILE_SIZE

FOV = pi / 3
NUM_RAYS = 10
STEP_ANGLE = FOV / NUM_RAYS
